parameters:
  featurefactory:
    feature_sources:
      - path: "./features_person"
        prefix: "local"

    catalog: "hive_metastore"
    database: "fs_demo_features_{entity}_global"

    features:
      latest_table: "features_latest"

    metadata:
      table: "metadata"

    checkpoint_dir: "dbfs:/odap-fs/checkpoints"
    checkpoint_interval: 5

    entities:
      person:
        id_column: "person_id"
        id_column_type: "long"
